# Generated by Django 6.0.3 on 2026-04-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('Title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Description', models.CharField()),
                ('Due_date', models.DateField()),
            ],
        ),
    ]
